version: "3.2"

services:
    {{projectName}}:
        build:
            context: .
        image: {{projectName}}
        hostname: {{projectName}}
        container_name: {{projectName}}
        env_file: .env
        depends_on:
            - nats
        networks:
            - docker-elk_elk
            - services

    nats:
        image: nats
        ports:
            - 4222:4222
        networks:
            - services

networks:
    docker-elk_elk:
        external: true
    services:
        driver: bridge

